###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "2.0"
services:

    api:
      image: nginx:alpine
      container_name: desafio-memed-api
      working_dir: /api
      volumes:
          - ./apps/api:/api
          - ./phpdocker/nginx/api.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    frontend:
      image: nginx:alpine
      container_name: desafio-memed-frontend
      working_dir: /frontend
      volumes:
          - ./apps/frontend:/frontend
          - ./phpdocker/nginx/frontend.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:8081"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: desafio-memed-php-fpm
      working_dir: /api
      volumes:
        - ./apps/api:/api
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

